<a href="https://colab.research.google.com/github/soham324/4NI25CS197_EXP_01/blob/main/DAV_lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
print("numpy version:",np.__version__)
print("pandas version:",pd.__version__)

numpy version: 2.0.2
pandas version: 2.2.3

In [ ]:
marks = np.array([45,67,78,89,68])
print("marks:",marks)
print("type:",type(marks))

marks: [45 67 78 89 68]
type: <class 'numpy.ndarray'>

In [ ]:
print("no. of dimensions:",marks.ndim)
print("shape:",marks.shape)
print("no. of elements:",marks.size)

no. of dimensions: 1
shape: (5,)
no. of elements: 5

In [ ]:
marks = np.array([45,67,78,89,68])
print("original:",marks)
print("add 5:",marks + 5)
print("multiply by 2:",marks * 2)
print("divide by 2:",marks / 2)
print("square:",marks **2)

original: [45 67 78 89 68]
add 5: [50 72 83 94 73]
multiply by 2: [ 90 134 156 178 136]
divide by 2: [22.5 33.5 39.  44.5 34. ]
square: [2025 4489 6084 7921 4624]

In [ ]:
print("sum:",marks.sum())
print("mean:",marks.mean())
print("maximum:",marks.max())
print("min:",marks.min())

sum: 347
mean: 69.4
maximum: 89
min: 45

In [ ]:
print("first mark",marks[0])
print("secomd mark",marks[1])
print("last mark:",marks[-1])

first mark 45
secomd mark 67
last mark: 68

In [ ]:
print("index 1 to 3",marks[1:4])
print("first 3:",marks[:3])
print("from index 2:",marks[2:])
print("every second element:",marks[::2])

index 1 to 3 [67 78 89]
first 3: [45 67 78]
from index 2: [78 89 68]
every second element: [45 78 68]

In [ ]:
student_marks = np.array([
    [56,67,78],
    [56,34,89],
    [67,89,90]
])
print("mean of all values:",student_marks.mean())
print("column wise mean:",student_marks.mean(axis=0))
print("row-wise mean:",student_marks.mean(axis=1))

mean of all values: 69.55555555555556
column wise mean: [59.66666667 63.33333333 85.66666667]
row-wise mean: [67.         59.66666667 82.        ]

In [ ]:
data ={ "Name":["Anu","Rahul","Kiran",'Priya'],
       "Branch":["CSE","AIML","CSE","AIML"],
        "Marks":[85,89,76,88]}
df = pd.DataFrame(data)
df

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML    891
2  Kiran    CSE     76
3  Priya   AIML     88

In [ ]:
print("Shape",df.shape)
print("\nColumns:")

print(df.columns)

Shape (4, 3)

Columns:
Index(['Name', 'Branch', 'Marks'], dtype='object')

In [ ]:
df.head()

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML    891
2  Kiran    CSE     76
3  Priya   AIML     88

In [ ]:
df.tail()

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML    891
2  Kiran    CSE     76
3  Priya   AIML     88

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Branch  4 non-null      object
 2   Marks   4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [ ]:
df.describe()

            Marks
count    4.000000
mean   285.000000
std    404.032177
min     76.000000
25%     82.750000
50%     86.500000
75%    288.750000
max    891.000000

In [ ]:
print("First row:")
print(df.iloc[1:4,0:3:2])

First row:
    Name  Marks
1  Rahul    891
2  Kiran     76
3  Priya     88

In [ ]:
high_scorers = df[df["Marks"] >= 85]
high_scorers

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML    891
3  Priya   AIML     88

In [ ]:
data = {
    "Name": ["sam","ram","pam","kam","tam"],
    "Department": ["CSE","ISE","CSE","AIML","ISE"],
    "Marks": [72,91,84,95,68],
    "Attendance": [82,94,88,96,75]
    }
students = pd.DataFrame(data)
students

  Name Department  Marks  Attendance
0  sam        CSE     72          82
1  ram        ISE     91          94
2  pam        CSE     84          88
3  kam       AIML     95          96
4  tam        ISE     68          75

In [ ]:
print("First row:")
print(students.iloc[1:5,0:3:2])

First row:
  Name  Marks
1  ram     91
2  pam     84
3  kam     95
4  tam     68

In [ ]:
hiks = students[students["Marks"] > 80]
hiks

  Name Department  Marks  Attendance
1  ram        ISE     91          94
2  pam        CSE     84          88
3  kam       AIML     95          96

In [ ]:
att = students[students["Attendance"] > 85]
att

  Name Department  Marks  Attendance
1  ram        ISE     91          94
2  pam        CSE     84          88
3  kam       AIML     95          96

In [ ]:
print("First row:")
print(students.iloc[1:4])

First row:
  Name Department  Marks  Attendance
1  ram        ISE     91          94
2  pam        CSE     84          88
3  kam       AIML     95          96

In [ ]:
avg = students.describe()
avg

           Marks  Attendance
count   5.000000    5.000000
mean   82.000000   87.000000
std    11.726039    8.660254
min    68.000000   75.000000
25%    72.000000   82.000000
50%    84.000000   88.000000
75%    91.000000   94.000000
max    95.000000   96.000000

In [ ]:
maxmarks = students[students["Department"] == "CSE"]
maxmarks

  Name Department  Marks  Attendance
0  sam        CSE     72          82
2  pam        CSE     84          88

In [ ]:
display(students[(students["Marks"] >= 80) & (students["Attendance"] > 85)])

  Name Department  Marks  Attendance
1  ram        ISE     91          94
2  pam        CSE     84          88
3  kam       AIML     95          96